modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/UncleClapton/KelpMisc"
license="BSD-3-Clause"

[[mods]]
modId="kelpmisc"
version="${file.jarVersion}"
displayName="Kelp Misc"
updateJSONURL="https://github.com/UncleClapton/KelpMisc/raw/main/update.json"
displayURL="https://github.com/UncleClapton/KelpMisc/releases"
logoFile="logo.png"
credits="UncleClapton"
authors="UncleClapton"
description='''
Hey there. Whatchu lookin at?!
'''

[[dependencies.kelpmisc]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kelpmisc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kelpmisc]]
    modId="simplefarming"
    mandatory=true
    versionRange="[1.16.4-1.3.5,)"
    side="BOTH"